server:
  port: 9999
  tomcat.uri-encoding: UTF-8
myini.lkbh: 9999
spring:
  application:
    name: dataTransfer
  datasource:
    from:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.80.253:1433;DatabaseName=sqlfb
      username: sa
      password: admin123
    to_cwlw:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.16:3306/cwlw?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    to_gt:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.16:3306/gt?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root